using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Fulcrum.ExtensionMethods;

public class EventState_4 : MonoBehaviour
{
    [SerializeField] private EventManager eventManager;
    [SerializeField] private int nextStateNumber;
    [SerializeField] GameObject[] activateTogglableGameObjects;

    public void ToggleShades()
    {
        activateTogglableGameObjects.ToggleGameObjectArray(true);
    }

    public void NextStateEvent()
    {
        eventManager.CallEvent(nextStateNumber);
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
